### ISSUE TITLE
DroidCam support

### ISSUE THREAD

**Issue by Tomako22** [deckerego/tally_pi#16]
Hello, i was very excited about your project, it was just what i needed. But after instal and some testing i couldnt get it to work properly. I tried multiple versions of your OBS script both python and lua, Script loads but no setting for lights IPs just color settings(see image). I just need the OBS script side to work. I also upload my last obs log. Thanks for response. Tomas

![image](https://user-images.githubusercontent.com/51489234/103445514-3a6c6900-4c75-11eb-9238-17625db3b180.png)
[2021-01-01 20-56-25.txt](https://github.com/deckerego/tally_pi/files/5759384/2021-01-01.20-56-25.txt)

**Comment by deckerego** [comment]
@Tomako22 - you should only load the Lua script at this point, unless your version of OBS has Python support built-in. Either way... best to only load the single Lua script as we troubleshoot.

It appears that your video input sources are registered as ffmpeg sources rather than video capture devices - that's likely the issue. Right now the script is just looking for video capture devices as sources.

How do you have your cameras connected?

**Comment by Tomako22** [comment]
@deckerego Okey, i use mainly DroidCam OBS Sources(https://dev47apps.com/obs/), i also tried usb webcam, usb videograbber. At least if can make it usable with Droidcam as source it would be very niec from u.

**Comment by deckerego** [comment]
Sure thing - I'll take a look at DroidCam and see how it works. I'm _guessing_ it registers itself as an ffmpeg stream - I'll see.

**Comment by Tomako22** [comment]
I woud be really gratefull, thanks.

**Comment by deckerego** [comment]
> I woud be really gratefull, thanks.

This should be ready for testing in the next few days - I see how the source is added now, but I'm trying not to bork other input sources. Will provide you with a test script to try out before I merge it into a release.

**Comment by deckerego** [comment]
@Tomako22 - when you get a chance, try out the new script at https://github.com/deckerego/tally_pi/blob/droidcam/scripts/obs_tally_light.lua - this should provide support for DroidCam input sources.

If it works for you let me know and I'll merge it in. Thanks!

**Comment by Tomako22** [comment]
Yeah, it work perfectly. Thanks man!! Would you also fix the python version? The poping up command line is bit annoying and also switching between sources takes bit longer than needed

**Comment by deckerego** [comment]
> Would you also fix the python version? The popping up command line is bit annoying and also switching between sources takes bit longer than needed

For the Python version - I haven't seen the popping up command line, but that's largely because OBS Python no longer works for MacOS and I can't really test anymore. The Lua script is now the only one I can test with unfortunately until MacOS gets Python support back.

**Comment by Tomako22** [comment]
Python loads properly, but the colour is functioning kinda weird. I'm getting blue-red when preview, Blue live, and blue-green idle.

**Comment by deckerego** [comment]
> ...the colour is functioning kinda weird. I'm getting blue-red when preview, Blue live, and blue-green idle.

Ah, I know what that is - I can probably blindly fix that. Created Issue #19 to resolve it.
