### ISSUE TITLE
Python script incorrectly interprets colors

### ISSUE THREAD

**Issue by deckerego** [deckerego/tally_pi#19]
@Tomako22 reports:
> Python loads properly, but the colour is functioning kinda weird. I'm getting blue-red when preview, Blue live, and blue-green idle.

Byte order is likely incorrect...

**Comment by Tomako22** [comment]
This works correctly for me.
        hexBlue = hexColor[4:6]
        hexGreen = hexColor[6:8]
	hexRed = hexColor[8:10]

**Comment by deckerego** [comment]
> This works correctly for me.
> hexBlue = hexColor[4:6]
> hexGreen = hexColor[6:8]
> hexRed = hexColor[8:10]

Yup, that mirrors https://github.com/deckerego/tally_pi/blob/master/scripts/obs_tally_light.lua#L118 - will change.

**Comment by deckerego** [comment]
> > This works correctly for me.
> > hexBlue = hexColor[4:6]
> > hexGreen = hexColor[6:8]
> > hexRed = hexColor[8:10]
> 
> Yup, that mirrors https://github.com/deckerego/tally_pi/blob/master/scripts/obs_tally_light.lua#L118 - will change.

Actually, I'm wrong, no it doesn't. I just didn't add the `0x` delimiter. My bad!

**Comment by deckerego** [comment]
Added your modifications - will be in next release. Thanks!
